### ISSUE TITLE
Schematron: Empty attribute values should not be reported as "Syntax error"

### ISSUE THREAD

**Issue by PullFrom** [AntennaHouse/focheck#13]
I am unsure, and cannot find anything in the spec that explains how empty attributes should be dealt with (like `initial-page-number=""`), but AHF must have a way how it deals with them. Are they ignored, or are they treated as if the default value would be present?

The Schematron check should give a useful message:

`'initial-page-number' should be auto | auto-odd | auto-even | <number> | inherit. '' is an empty String.`

**Comment by tgraham-antenna** [comment]
Repeating property values from spec for shorthands and other otherwise-ignored properties, but they're not very readable because oXygen won't stop escaping '<' and '>' in messages until oXygen 17.1.  See http://www.oxygenxml.com/pipermail/oxygen-user/2015-June/005512.html

Also because '<' and '>' aren't escaped, reporting BNF production names for other properties.  They're not very readable either.

oXygen's tooltip does show a readable version of the values from the spec, but you won't see that in the main editor window while oXygen is reporting a Schematron warning for the empty property value.
