### ISSUE TITLE
Error in Schematron for XSL-FO containing table

### ISSUE THREAD

**Issue by raducoravu** [AntennaHouse/focheck#41]
The problem was reported here:

https://www.oxygenxml.com/forum/viewtopic.php?p=57350#p57350
I'm attaching a sample XSL-FO file, validating it yelds:

       An empty sequence is not allowed as the first argument of ahf:parser-runner()

[sample.zip](https://github.com/AntennaHouse/focheck/files/4261898/sample.zip)

**Comment by tgraham-antenna** [comment]
Included in **focheck** 0.7.5.

**Comment by raducoravu** [comment]
Thanks @tgraham-antenna

**Comment by jocrow** [comment]
validation issues resolved and confirmed in focheck 0.7.5.

however, installing the add-on update in oXygen 22.0 fails due to incorrect :

<xt:location href="https://github.com/AntennaHouse/focheck/releases/download/v0.7.5/focheck-framework-0.7.5.zip"/>

should be 

<xt:location href="https://github.com/AntennaHouse/focheck/releases/download/0.7.5/focheck-framework-0.7.5.zip"/>
![IDE-add-on-issues](https://user-images.githubusercontent.com/662117/76427103-3270cf00-63ac-11ea-9664-d7e62b14ed9b.png)
![corrective_IDE-add-on-issues](https://user-images.githubusercontent.com/662117/76427105-33096580-63ac-11ea-8464-0ce04855445c.png)

Best,
Jocrow

**Comment by tgraham-antenna** [comment]
I fixed this without commenting on it, sorry.

The file defining the oXygen add-on is generated automatically, and it always includes the `v` in the URL.

The tag on the GitHub repository is created manually and is sometimes subject to human error.  The tag should always start with `v`.

There is probably a GitHub API that I could use to automate making the releases, but I haven't looked into it.
