### ISSUE TITLE
max-/min-width/-height are missing for or fo:external-graphic

### ISSUE THREAD

**Issue by PullFrom** [AntennaHouse/focheck#6]
It seems the four properties max-height, max-width, min-height, min-width are not listed in the spec as being valid for <fo:external-graphic>. 

In the spec in the section about <fo:external-graphic>, "max-height" is mentioned in a note, but not listed under the properties applicable.

Maybe one need a better grip at understanding the spec?

We are also using those properties with <fo:block>, but I am not sure whether this should be working.

**Comment by tgraham-antenna** [comment]
There's two parts to this:
- XSL (or its editors) had an uneasy relationship with CSS,  `max-height`, etc., are copied from CSS (see the meaning of the black border from http://www.w3.org/TR/xsl/#d0e15664), and because they're not listed as properties of `fo:block-container`, etc., the stylesheet that dumps the Relax NG wasn't picking them up.  They've now been added using the same mechanism as for adding shorthands.
- In my testing, AH Formatter doesn't complain about `max-width`, etc., on `fo:block`, but also doesn't honor them.

**Comment by tgraham-antenna** [comment]
Now allowed by the schema.
